services:
  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: jiya
      POSTGRES_PASSWORD: jiya
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      - postgres

  servicereg:
    image: jiya2802/servicereg:latest
    container_name: servicereg
    ports:
      - "8761:8761"
    depends_on:
      - rabbitmq
      - zipkin
      - postgres
      - pgadmin
    networks:
      - postgres
      - microservice-network

  companyms:
    image: jiya2802/companyms:latest
    container_name: company
    ports:
      - "8081:8081"
    depends_on:
      - servicereg
    networks:
      - postgres
      - microservice-network
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  jobms:
    image: jiya2802/jobms:latest
    container_name: job
    ports:
      - "8082:8082"
    depends_on:
      - servicereg
    networks:
      - postgres
      - microservice-network
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://servicereg:8761/eureka

  reviewms:
    image: jiya2802/reviewms:latest
    container_name: review
    ports:
      - "8080:8080"
    depends_on:
      - servicereg
    networks:
      - postgres
      - microservice-network
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  gateway-ms:
    image: jiya2802/gatewayms:latest
    container_name: gateway
    ports:
      - "8084:8084"
    depends_on:
      - servicereg
    networks:
      - postgres
      - microservice-network
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    ports:
      - "9411:9411"
    networks:
      - postgres

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - postgres

networks:
  microservice-network:
    driver: bridge
  postgres:
    driver: bridge

volumes:
  postgres:
  pgadmin:
